universitarios/core/urls.py
from django.urls import path, include
from django.conf.urls import include, url
from . import views
import users.urls
import dashboard.urls
import dashboard.views
app_name = 'core'

urlpatterns = [
    path(   '',views.HomePageView.as_view(),name = 'Home'),

]

universitarios/dashboard/urls.py
from django.urls import path, include
from django.conf.urls import include, url
from . import views
import users.urls
import core.urls

app_name = 'dashboard'
urlpatterns = [
    path('adm/', views.adm.as_view(), name='adm'),
    path('socio/', views.socio, name='socio'),
    path('content/', views.load_content, name='load_content'),
    path('position/', views.add_position_ok, name='add_position_ok'),
    path('record/', views.add_record_ok, name='add_record_ok'),
    path('player/', views.add_player_ok, name='add_player_ok'),
    path('match/', views.add_match_ok, name='add_match_ok'),
    path('training/', views.add_training_ok, name='add_training_ok'),
    path('measure/', views.add_measure_ok, name='add_measure_ok'),
    path('Assistance/', views.mark_assistance_ok, name='mark_assistance_ok'),
    path('Minute/', views.mark_assistance_ok, name='add_minute_ok'),

]

universitarios/universitarios/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import static
import core.urls
import users.urls
import dashboard.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(core.urls,namespace='core')),
    path('users/', include(users.urls,namespace='users')),
    path('dashboard/', include(dashboard.urls,namespace='dashboard')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT)

universitarios/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from mapbox_location_field.models import LocationField
from mapbox_location_field.spatial.models import SpatialLocationField
from phonenumber_field.modelfields import PhoneNumberField
import datetime
from vote.models import VoteModel

# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):  
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to = 'postImage/')
    def delete(self, *args, **kwargs):
        # Delete image file also
        storage, path = self.image.storage, self.image.path
        super(ImageModel, self).delete(*args, **kwargs)
        storage.delete(path)
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Directive (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True,null=True)
    position =  models.CharField(max_length=100)
    start_date = models.DateField(null=True, blank=True)
    end_date  = models.DateField(null=True, blank=True)
    status =  models.TextField()
    class Meta:
        verbose_name = 'Directiva'
        verbose_name_plural = 'Miembros de la Directiva'
    def __str__(self):
        return str(self.position+" "+self.user.name)

class Minute(models.Model):
    table = models.TextField('Tabla',)
    date = models.DateField('Fecha',)
    location =  models.CharField('Ubicación',max_length=250)
    locationGPS = LocationField(null=True, blank=True, 
            map_attrs={"center": [-71.24076894770667,-29.915835830267262], 
            "marker_color": "blue",
            "placeholder": "Lugar de reunión",})
    content = models.TextField('Contenido')
    users = models.ManyToManyField(User, through='Minute_Assistants')
    class Meta:
        verbose_name = 'Acta'
        verbose_name_plural = 'Actas'
    def __str__(self):
        return str(self.table+" "+self.location)

class Minute_Assistants(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    minute = models.ForeignKey(Minute, on_delete=models.CASCADE,)
    observation = models.TextField()
    class Meta:
        verbose_name = 'Asistentes a Acta'
        verbose_name_plural = 'Asistentes a Actas'
    def __str__(self):
        return str(self.user+" "+self.minute)

class Isue(VoteModel,models.Model):
    title =  models.CharField('Titulo',max_length=100)
    content = models.TextField('Contenido',)
    minute = models.ForeignKey(Minute, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'
    def __str__(self):
        return self.title

universitarios/dashboard/views.py
import simplejson as simplejson
from datetime import datetime as dt
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.db import transaction
from django.views.generic import  TemplateView
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template.loader import render_to_string
from functools import partial
from django.template import RequestContext
from users.models import Profile
from core.models import Minute, Isue
from dashboard.models import Position, Player, Match, Training, Assistants, Measure, Record
from dashboard.forms import PositionForm, PlayerForm, RecordForm, MatchForm, TrainingForm, MeasureForm, AssistanceForm
from core.forms import MinuteForm
from django.contrib import messages 
from django.contrib.auth.models import Group


# Create your views here.
class adm(TemplateView):
    template_name = "home2.html"
def socio(request):
    is_partner = request.user.groups.filter(name__in=['socio']).exists()
    is_player = request.user.groups.filter(name__in=['jugador']).exists()
    is_directive = request.user.groups.filter(name__in=['directiva']).exists()
    is_coach   = request.user.groups.filter(name__in=['entrenador']).exists()  
    if is_directive: 
        return render(request, 'dashboard.html',context)
    if is_player:
        minutes = Minute.objects.all()
        isues = Isue.objects.all()
        exist = hasattr(request.user, 'player')
        return render(request, 'dashboard2.html',{'minutes':minutes,'isues':isues,'exist':exist})
    if is_partner:
        minutes = Minute.objects.all()
        isues = Isue.objects.all()
        return render(request, 'dashboard2.html',{'minutes':minutes,'isues':isues})
    if is_coach:
        return render(request, 'dashboard2.html',)


@csrf_protect       
def load_content(request):
    if request.POST and request.is_ajax:
        data = request.POST['click_id']
        response_data = type_of_request(data,request)
        return HttpResponse(response_data)

def get_minute(ids,request):
    minute = Minute.objects.get(id=ids)
    return render_to_string("content/minute.html",{'minute': minute })
def get_isue(ids,request):
    isue = Isue.objects.get(id=ids)
    return render_to_string("content/isue.html",{'isue': isue })
def get_register(ids,request):
    isue = Isue.objects.get(id=ids)
    return render_to_string("content/register-all.html",{'isue': isue })
def add_register(ids,request):
    return render_to_string("content/register.html",{})
def add_position(CreateView,request):
    template_name = "content/new_position.html"
    form_class = PositionForm
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_position.html",{'form':form_class},request)
def add_player(CreateView,request):
    template_name = "content/new_player.html"
    form_class = PlayerForm
    exist = hasattr(request.user, 'player')
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_player.html",{'form':form_class,'exist':exist},request)
def add_record(CreateView,request):
    template_name = "content/new_record.html"
    form_class = RecordForm
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_record.html",{'form':form_class},request)
def add_measure(CreateView,request):
    template_name = "content/new_measure.html"
    form_class = MeasureForm
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_measure.html",{'form':form_class},request)
def add_match(CreateView,request):
    template_name = "content/new_match.html"
    form_class = MatchForm
    options = Match.objects.values_list('opponent', flat=True)
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_match.html",{'form':form_class,'options':options},request)
def add_training(CreateView,request):
    template_name = "content/new_training.html"
    form_class = TrainingForm
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_training.html",{'form':form_class},request)
def see_training(ids,request):
    trainings = Training.objects.all()
    return render_to_string("content/see_training.html",{'trainings': trainings })
def mark_assistance(CreateView,request):
    last_training = Training.objects.filter(date__lte=dt.today()).order_by('-date').first()
    template_name = "content/mark_assistance.html"
    form_class = AssistanceForm(initial={'player': request.user.player, 'training': last_training})
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/mark_assistance.html",{'form':form_class},request)
def add_minute(CreateView,request):
    template_name = "content/new_minute.html"
    form_class = MinuteForm
    def get_success_url(self):
        return reverse('dashboard:socio')
    return render_to_string("content/new_minute.html",{'form':form_class},request)
def achievement(ids,request):
    records = Record.objects.order_by('name')
    
    for record in records :
        measure = []
        labels = []
        data = []

    queryset = City.objects.order_by('-population')[:5]
    for city in queryset:
        labels.append(city.name)
        data.append(city.population)

    return render_to_string("content/pie_chart.html", {
        'labels': labels,
        'data': data,
    })
def vote(messaje,request):
    action = messaje.split('/')[1]
    ids = messaje.split('/')[0]
    isue = Isue.objects.get(id=ids)
    if not isue.votes.exists(request.user.id):
        if action=="+": 
            isue.votes.up(request.user.id)
            return "Exito, ha votado a favor"
        if action=="-":
            isue.votes.down(request.user.id)
            return "Exito, ha votado en contra"
    return "ya ha votado en este punto"

def type_of_request(messaje,request):
    action = ""
    action = messaje.split('|')[0]
    ids = messaje.split('|')[1]
    switcher = {
        'get_isue': get_isue,
        'get_minute': get_minute,
        'get_register': get_register,
        'add_record': add_record,
        'add_measure': add_measure,
        'add_position':add_position,
        'add_player':add_player,
        'add_match':add_match,
        'add_minute':add_minute,
        'add_training':add_training,
        'see_training':see_training,
        'mark_assistance':mark_assistance,
        'vote':vote,
        'achievement':achievement,
    }
    return switcher[action](ids,request)

def add_position_ok(request): 
    context = RequestContext(request)
    if request.method == 'POST':
        form = PositionForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('dashboard:socio'))
    return HttpResponseRedirect(reverse('dashboard:socio'))
def add_training_ok(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = TrainingForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('dashboard:socio'))
    error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
    return HttpResponse(simplejson.dumps(error_string))
def add_match_ok(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = MatchForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('dashboard:socio'))
        error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
        return HttpResponse(simplejson.dumps(error_string))
def add_measure_ok(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = MeasureForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.player = request.user.player
            obj.save()
            return HttpResponseRedirect(reverse('dashboard:socio'))
        error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
        return HttpResponse(simplejson.dumps(error_string))
def add_record_ok(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('dashboard:socio'))
    return HttpResponseRedirect(reverse('dashboard:socio'))
def add_player_ok(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            obj, created = Player.objects.update_or_create(
                user=request.user,
                defaults=form.cleaned_data
            )
            if created:
                my_group = Group.objects.get(name='jugador') 
                my_group.user_set.add(request.user)
                return HttpResponse(simplejson.dumps('Exito, ha sido creado como jugador'))
            if not created :
                return HttpResponse(simplejson.dumps('Exito, sus datatos fueron actualizados'))
        error_string = ' '.join([' '.join(x for x in l) for l in list(form.errors.values())])
        return HttpResponse(simplejson.dumps(error_string))
def mark_assistance_ok(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = AssistanceForm(request.POST)
        if form.is_valid():
            obj, created = Assistants.objects.update_or_create(
                player=request.user.player,
                training = Training.objects.filter(date__lte=dt.today()).order_by('-date').first(),

universitarios/dashboard/templates/content/isue.html
{% block isue_block %}
<div>
    {% autoescape off %}
    <div class="new-content">
        <h2>{{ isue.title }}</h2>
        <h5>{{ isue.date }}</h5>
        <h3>Contenido del punto:</h3> {{ isue.content|linebreaks }}
    </div>
    {% endautoescape %}
    <div>
        <form id="formABC" action="#" method="POST">
            <h5>Votación: ¿Está usted de acuerdo con el punto?</h3>
                <a class="likebutton btn btn-primary btn-lg" id="vote" href="#" data-catid="vote|{{ isue.id }}/+">Apruebo</a>
                <a class="likebutton btn btn-primary btn-lg" id="vote" href="#" data-catid="vote|{{ isue.id }}/-">Rechazo</a>
        </form>
    </div>
</div>
{% endblock isue_block %}

<script>
    $(document).on('click', '#vote', function(e) {
        event.stopImmediatePropagation(); 
        var id;
        id = $(this).attr("data-catid");
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        $.ajax({
            type: "POST",
            url: "{% url 'dashboard:load_content' %}",
            headers: {
                "X-CSRFToken": csrftoken
            },
            data: {
                click_id: id,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            cache: true,
            success: function(data) {
                alert(data);
            },
            error: function(xhr, ajaxOptions, thrownError) {
                console.log('xHR: ' + xhr);
                console.log('ajaxOption: ' + ajaxOptions);
                console.log('thrownError: ' + thrownError);
            }
        });
        
    });
   
</script>

universitarios/dashboard/templates/content/mark_assistance.html
{% block assistance_block %}
<div>
    {% load static %}

    <form  id="myForm"  action="{% url 'dashboard:mark_assistance_ok' %}" method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
        <div class="row h-90">
            <div class="col-md-12 my-auto">
                <div class="card card-block col-xs-12 col-md-12 box p-3 mx-auto">
                    <div class="container">
                        <h1><strong>Marcar Asistencia</strong>
                        </h1>
                    </div>
                    {% for field in form %}
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ field.label }}</label>
                        <div class="col-xs-12">
                            {{ field }}
                        </div>
                    </div>
                    
                    {% endfor %}
                    <input class="btn btn-primary col-xs-offset-1 col-xs-12" type="submit" value="Marcar Asistencia" />
                    {% if form.errors %}
                    <!-- Error messaging -->
                    <div id="errors">
                        <div class="inner">
                            <p>Existen errores en la información. Por favor corrige lo siguiente:</p>
                            {{ form.non_field_errors }}
                            <ul>
                                {% for field in form %} {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %} {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- /Error messaging -->
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    // wait for the DOM to be loaded 
    $(document).ready(function() { 
        // bind 'myForm' and provide a simple callback function 
        $('#myForm').ajaxForm(function(data) { 
            alert(data)
            window.location.reload();
        }); 
    }); 
</script>
<style>
    body {
        background: whitesmoke;
        font-family: 'Open Sans', sans-serif;
    }
    
    .container {
        margin: 30px auto;
        padding: 20px;
    }
    
    h1 {
        font-size: 20px;
        text-align: center;
        margin: 20px 0 20px;
    }
    
    h1 small {
        display: block;
        font-size: 15px;
        padding-top: 8px;
        color: gray;
    }
    
    .btn-primary,
    .btn-primary:hover {
        background-color: rgb(21, 82, 212) !important;
    }
    
    .btn-primary,
    .btn-primary:active {
        background-color: rgb(87, 236, 1) !important;
    }
    
    .btn-primary,
    .btn-primary:visited {
        background-color: #8064A2 !important;
    }
</style>
{% endblock assistance_block %}

universitarios/dashboard/templates/content/minute.html
{% block minute_block %}
<div>
    {% autoescape off %}
    <div class="new-content">
        <h2>{{ minute.location }}</h2>
        <h5>{{ minute.date }}</h5>
        <h3>Contenido del acta:</h3> {{ minute.content|linebreaks }}
    </div>
    <div>
        <ul>
            {% for isue in minute.isue_set.all %}
            <li>
                <a class="click" href="#" data-catid="get_isue|{{isue.id}}" id="isue{{isue.id}}">                                        
                    {{ isue.title }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endautoescape %}
</div>
{% endblock minute_block %}

universitarios/dashboard/templates/content/new_match.html
{% block match_block %}
<div>
    {% load static %}
    <form action="{% url 'dashboard:add_match_ok' %}" method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
        <div class="row h-90">
            <div class="col-md-12 my-auto">
                <div class="card card-block col-xs-12 col-md-12 box p-3 mx-auto">
                    <div class="container">
                        <h1><strong>Crear Partido</strong>
                        </h1>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-12" for="name">{{ form.opponent.label }}:</label>
                        <div class="col-xs-12">
                            <select class ="float-right btn btn-secondary dropdown-toggle w-100 form-control"onchange="this.nextElementSibling.value=this.value">
                                <option value=""></option>
                                {% for field in options %}
                                <option value="{{ field }}">{{ field }}</option>
                                {% endfor %}
                            </select>
                            {{ form.opponent }} 
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ form.points_infavor.label }}:</label>
                        <div class="col-xs-12">
                            {{ form.points_infavor }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ form.points_against.label }}:</label>
                        <div class="col-xs-12">
                            {{ form.points_against }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ form.winnig.label }}:</label>
                        <div class="col-xs-12">
                            {{ form.winnig }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ form.observation.label }}:</label>
                        <div class="col-xs-12">
                            {{ form.observation }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label style="text-align: left;"class="control-label col-xs-12" for="name">
                            {{ form.date.label }}
                        </label>
                        <div class="col-xs-12">
                            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                                {{ form.date }}
                                <div class="input-group-append " data-target="#datetimepicker1" data-toggle="datetimepicker">
                                    <div class="input-group-text">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ form.duration.label }}:</label>
                        <div class="col-xs-12">
                            {{ form.duration }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label style="text-align: left;"class="control-label col-xs-12" for="name">
                            {{ form.players.label }}
                        </label>
                        <div class="form-group input-group mb-3" style="height:200px; width:50%;overflow:hidden; overflow-y:scroll;">
                            <div class="col-xs-12">
                                {{ form.players }}
                            </div>                        
                        </div>
                    </div>
                    <input class="btn btn-primary col-xs-offset-1 col-xs-12" type="submit" value="Crear" />
                    {% if form.errors %}
                    <!-- Error messaging -->
                    <div id="errors">
                        <div class="inner">
                            <p>Existen errores en la información. Por favor corrige lo siguiente:</p>
                            {{ form.non_field_errors }}
                            <ul>
                                {% for field in form %} {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %} {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- /Error messaging -->
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
</div>
<style>
    .select-editable select {
        position:absolute;
        top:0px;
        left:0px;
        font-size:14px;
        border:none;
        width:120px;
        margin:0;
    }
    .select-editable input {
        position:absolute;
        top:0px;
        left:0px;
        width:100px;
        padding:1px;
        font-size:12px;
        border:none;
    }
    .select-editable select:focus, .select-editable input:focus {
        outline:none;
    }
    .btn-primary,
    .btn-primary:hover {
        background-color: rgb(21, 82, 212) !important;
    }
    
    .btn-primary,
    .btn-primary:active {
        background-color: rgb(87, 236, 1) !important;
    }
    
    .btn-primary,
    .btn-primary:visited {
        background-color: #8064A2 !important;
    }
</style>
<script>
    $(function () {
        $("#datetimepicker1").datepicker({
        });
    });
</script>
<script>
    // wait for the DOM to be loaded 
    $(document).ready(function() { 
        // bind 'myForm' and provide a simple callback function 
        $('#myForm').ajaxForm(function(data) { 
            alert(data)
            window.location.reload();
        }); 
    }); 
</script>
{% endblock match_block %}

universitarios/dashboard/templates/content/new_measure.html
{% block measure_block %}
<div>
    {% load static %}

    <form action="{% url 'dashboard:add_measure_ok' %}" method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
        <div class="row h-90">
            <div class="col-md-12 my-auto">
                <div class="card card-block col-xs-12 col-md-12 box p-3 mx-auto">
                    <div class="container">
                        <h1><strong>Agregar Logro</strong>
                        </h1>
                    </div>
                    {% for field in form %}
                    <div class="form-group">
                        <label class="control-label col-xs-1" for="name">{{ field.label }}</label>
                        <div class="col-xs-12">
                            {{ field }}
                        </div>
                    </div>
                    {% endfor %}
                    <input class="btn btn-primary col-xs-offset-1 col-xs-12" type="submit" value="Crear" />
                    {% if form.errors %}
                    <!-- Error messaging -->
                    <div id="errors">
                        <div class="inner">
                            <p>Existen errores en la información. Por favor corrige lo siguiente:</p>
                            {{ form.non_field_errors }}
                            <ul>
                                {% for field in form %} {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %} {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- /Error messaging -->
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
</div>
<style>
    body {
        background: whitesmoke;
        font-family: 'Open Sans', sans-serif;
    }
    
    .container {
        margin: 30px auto;
        padding: 20px;
    }
    
    h1 {
        font-size: 20px;
        text-align: center;
        margin: 20px 0 20px;
    }
    
    h1 small {
        display: block;
        font-size: 15px;
        padding-top: 8px;
        color: gray;
    }
    
    .btn-primary,
    .btn-primary:hover {
        background-color: rgb(21, 82, 212) !important;
    }
    
    .btn-primary,
    .btn-primary:active {
        background-color: rgb(87, 236, 1) !important;
    }
    
    .btn-primary,
    .btn-primary:visited {
        background-color: #8064A2 !important;
    }
</style>
{% endblock measure_block %}

universitarios/dashboard/templates/content/see_training.html
{% block register_block %}
<div>
    {% load static %}

        <div class="row h-90">
            <div class="col-md-12 my-auto">
                <div class="card card-block col-xs-12 col-md-12 box p-3 mx-auto">
                    <div class="container">
                        <h1><strong>Ver Entrenamientos</strong>
                        </h1>
                    </div>
                    <ul class="list-group">
                        {% for training in trainings %}
                        <li class="list-group-item" >
                            <a class="click" href="#" data-catid="get_training|{{training.id}}" id="training{{training.id}}">                                        
                                {{ training.place }}, fecha: {{ training.date }}
                            </a>
                        </li>
                    {% endfor %} 
                    </ul>   
                </div>
            </div>
        </div>

    <style>
        body {
            background: whitesmoke;
            font-family: 'Open Sans', sans-serif;
        }
        
        .container {
            margin: 30px auto;
            padding: 20px;
        }
        
        h1 {
            font-size: 20px;
            text-align: center;
            margin: 20px 0 20px;
        }
        
        h1 small {
            display: block;
            font-size: 15px;
            padding-top: 8px;
            color: gray;
        }
        
        .btn-primary,
        .btn-primary:hover {
            background-color: rgb(21, 82, 212) !important;
        }
        
        .btn-primary,
        .btn-primary:active {
            background-color: rgb(87, 236, 1) !important;
        }
        
        .btn-primary,
        .btn-primary:visited {
            background-color: #8064A2 !important;
        }
    </style>
    
</div>
{% endblock register_block %}